const nowPlayMovies: NowPlayMovie[] = [
  {
    adult: false,
    backdrop_path: '/18TSJF1WLA4CkymvVUcKDBwUJ9F.jpg',
    genre_ids: [27, 53],
    id: 1034541,
    original_language: 'en',
    original_title: 'Terrifier 3',
    overview:
      "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
    popularity: 7119.469,
    poster_path: '/63xYQj1BwRFielxsBDXvHIJyXVm.jpg',
    release_date: '2024-10-09',
    title: 'Terrifier 3',
    video: false,
    vote_average: 7.298,
    vote_count: 544,
  },
  {
    adult: false,
    backdrop_path: '/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg',
    genre_ids: [878, 28, 12],
    id: 912649,
    original_language: 'en',
    original_title: 'Venom: The Last Dance',
    overview:
      "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    popularity: 6160.532,
    poster_path: '/k42Owka8v91trK1qMYwCQCNwJKr.jpg',
    release_date: '2024-10-22',
    title: 'Venom: The Last Dance',
    video: false,
    vote_average: 6.7,
    vote_count: 442,
  },
  {
    adult: false,
    backdrop_path: '/4zlOPT9CrtIX05bBIkYxNZsm5zN.jpg',
    genre_ids: [16, 878, 10751],
    id: 1184918,
    original_language: 'en',
    original_title: 'The Wild Robot',
    overview:
      "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    popularity: 5275.345,
    poster_path: '/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    release_date: '2024-09-12',
    title: 'The Wild Robot',
    video: false,
    vote_average: 8.54,
    vote_count: 2304,
  },
  {
    adult: false,
    backdrop_path: '/bFPqSvR2EmWQ9AlzWkC801XpoAZ.jpg',
    genre_ids: [18, 27, 878],
    id: 933260,
    original_language: 'en',
    original_title: 'The Substance',
    overview:
      'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
    popularity: 3439.676,
    poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
    release_date: '2024-09-07',
    title: 'The Substance',
    video: false,
    vote_average: 7.3,
    vote_count: 1299,
  },
  {
    adult: false,
    backdrop_path: '/uGmYqxh8flqkudioyFtD7IJSHxK.jpg',
    genre_ids: [18, 80, 53],
    id: 889737,
    original_language: 'en',
    original_title: 'Joker: Folie à Deux',
    overview:
      "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
    popularity: 3019.565,
    poster_path: '/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg',
    release_date: '2024-10-01',
    title: 'Joker: Folie à Deux',
    video: false,
    vote_average: 5.675,
    vote_count: 1294,
  },
  {
    adult: false,
    backdrop_path: '/oPUOpnl3pqD8wuidjfUn17mO1yA.jpg',
    genre_ids: [16, 878, 12, 10751, 28],
    id: 698687,
    original_language: 'en',
    original_title: 'Transformers One',
    overview:
      'The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.',
    popularity: 3135.612,
    poster_path: '/iHPIBzrjJHbXeY9y7VVbEVNt7LW.jpg',
    release_date: '2024-09-11',
    title: 'Transformers One',
    video: false,
    vote_average: 8.128,
    vote_count: 509,
  },
  {
    adult: false,
    backdrop_path: '/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg',
    genre_ids: [10749, 18],
    id: 1079091,
    original_language: 'en',
    original_title: 'It Ends with Us',
    overview:
      "When a woman's first love suddenly reenters her life, her relationship with a charming, but abusive neurosurgeon is upended, and she realizes she must learn to rely on her own strength to make an impossible choice for her future.",
    popularity: 1064.586,
    poster_path: '/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg',
    release_date: '2024-08-07',
    title: 'It Ends with Us',
    video: false,
    vote_average: 7.189,
    vote_count: 966,
  },
  {
    adult: false,
    backdrop_path: '/llIXQAndg5kB6SWlp6ouUdO7Zxd.jpg',
    genre_ids: [12, 36, 28, 18, 10749, 53],
    id: 1084736,
    original_language: 'fr',
    original_title: 'Le Comte de Monte-Cristo',
    overview:
      'Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.',
    popularity: 1773.12,
    poster_path: '/r7iCXrXmq4hKpB4QfDzZd8vsJ7l.jpg',
    release_date: '2024-06-28',
    title: 'The Count of Monte-Cristo',
    video: false,
    vote_average: 8.3,
    vote_count: 728,
  },
  {
    adult: false,
    backdrop_path: '/csQSGH0QU8D3Ov5YLEYuHep8ihA.jpg',
    genre_ids: [53, 12, 28, 878],
    id: 1196470,
    original_language: 'fr',
    original_title: 'Survivre',
    overview:
      'A couple celebrates their son’s birthday in the middle of the ocean on their boat. A violent storm hits and it brings up hungry creatures from the depths and they fight for their survival.',
    popularity: 1469.299,
    poster_path: '/7fR3KxswtY8OHHZuOUB9td58CRX.jpg',
    release_date: '2024-06-19',
    title: 'Survive',
    video: false,
    vote_average: 4.814,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: '/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg',
    genre_ids: [35, 14, 27],
    id: 917496,
    original_language: 'en',
    original_title: 'Beetlejuice Beetlejuice',
    overview:
      "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
    popularity: 1181.733,
    poster_path: '/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg',
    release_date: '2024-09-04',
    title: 'Beetlejuice Beetlejuice',
    video: false,
    vote_average: 7.157,
    vote_count: 1696,
  },
  {
    adult: false,
    backdrop_path: '/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg',
    genre_ids: [27, 53],
    id: 663712,
    original_language: 'en',
    original_title: 'Terrifier 2',
    overview:
      "A year after the Miles County massacre, Art the Clown is resurrected by a sinister entity. Art returns home, where he must hunt down and destroy teenage Sienna and her younger brother Jonathan on Halloween. As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
    popularity: 1179.97,
    poster_path: '/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg',
    release_date: '2022-10-06',
    title: 'Terrifier 2',
    video: false,
    vote_average: 6.8,
    vote_count: 1942,
  },
  {
    adult: false,
    backdrop_path: '/uLqNGzJwnj8JKkKuRM2dHWJKCtc.jpg',
    genre_ids: [28, 27, 53],
    id: 1029235,
    original_language: 'en',
    original_title: 'Azrael',
    overview:
      'In a world where no one speaks, a devout female hunts down a young woman who has escaped her imprisonment. Recaptured by its ruthless leaders, Azrael is due to be sacrificed to pacify an ancient evil deep within the surrounding wilderness.',
    popularity: 1475.718,
    poster_path: '/qpdFKDvJS7oLKTcBLXOaMwUESbs.jpg',
    release_date: '2024-09-27',
    title: 'Azrael',
    video: false,
    vote_average: 6.1,
    vote_count: 111,
  },
  {
    adult: false,
    backdrop_path: '/6Rjsm5khNaYa4Gnw4iHnGX2E34T.jpg',
    genre_ids: [27, 53],
    id: 1063877,
    original_language: 'en',
    original_title: "Don't Move",
    overview:
      'A grieving woman in a secluded forest encounters a killer who injects her with a paralytic drug. As her body shuts down, her fight for survival begins.',
    popularity: 1182.247,
    poster_path: '/cRDJxdnRb7ikKd6fVJTrGeaL34v.jpg',
    release_date: '2024-10-24',
    title: "Don't Move",
    video: false,
    vote_average: 6.545,
    vote_count: 342,
  },
  {
    adult: false,
    backdrop_path: '/begseNUKhZcc05Bc1UggaX5GeES.jpg',
    genre_ids: [28, 53, 80],
    id: 976734,
    original_language: 'en',
    original_title: 'Canary Black',
    overview:
      'Top level CIA agent Avery Graves is blackmailed by terrorists into betraying her own country to save her kidnapped husband. Cut off from her team, she turns to her underworld contacts to survive and help locate the coveted intelligence that the kidnappers want.',
    popularity: 1406.847,
    poster_path: '/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg',
    release_date: '2024-10-10',
    title: 'Canary Black',
    video: false,
    vote_average: 6.418,
    vote_count: 159,
  },
  {
    adult: false,
    backdrop_path: '/mpMDztY5OmV7i4ypYpWgqsP4DHs.jpg',
    genre_ids: [27, 53],
    id: 978796,
    original_language: 'en',
    original_title: 'Bagman',
    overview:
      'For centuries and across cultures, parents have warned their children of the legendary Bagman, who snatches innocent children and stuffs them into his vile, rotting bag—never to be seen again. Patrick McKee narrowly escaped such an encounter as a boy, which left him with lasting scars throughout his adulthood. Now, Patrick’s childhood tormentor has returned, threatening the safety of his wife Karina and son Jake.',
    popularity: 838.107,
    poster_path: '/pkKcIP2B2ILAh4lGKyn9YkO0L1t.jpg',
    release_date: '2024-09-20',
    title: 'Bagman',
    video: false,
    vote_average: 6.6,
    vote_count: 49,
  },
  {
    adult: false,
    backdrop_path: '/hd1TvTUGjkoYoqvXYfSBpI5Ri9B.jpg',
    genre_ids: [16, 28, 12, 878],
    id: 1159311,
    original_language: 'ja',
    original_title: '僕のヒーローアカデミア THE MOVIE ユアネクスト',
    overview:
      "In a society devastated by the effects of an all-out war between heroes and villains, a mysterious giant fortress suddenly appears, engulfing towns and people one after another. Then, a man reminiscent of All Might, the 'symbol of peace', stands in front of Izuku and his friends...",
    popularity: 821.294,
    poster_path: '/8rdB1wkheEMMqcY8qLAKjCMPcnZ.jpg',
    release_date: '2024-08-02',
    title: "My Hero Academia: You're Next",
    video: false,
    vote_average: 6.798,
    vote_count: 42,
  },
  {
    adult: false,
    backdrop_path: '/epQfhIcfqWgrMhRvnxkVm7EeEpE.jpg',
    genre_ids: [878, 27],
    id: 1125510,
    original_language: 'es',
    original_title: 'El hoyo 2',
    overview:
      'After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.',
    popularity: 888.176,
    poster_path: '/hf94ySIzdP3KwHau9VSWh7b7Qu2.jpg',
    release_date: '2024-09-27',
    title: 'The Platform 2',
    video: false,
    vote_average: 5.7,
    vote_count: 776,
  },
  {
    adult: false,
    backdrop_path: '/vOwezqxpHjBpA5nJIWbapm9Qtgd.jpg',
    genre_ids: [28, 35, 80],
    id: 616446,
    original_language: 'en',
    original_title: 'Brothers',
    overview:
      "A reformed criminal's attempt at going straight is derailed when he reunites with his sanity-testing twin brother on a road trip for the score of a lifetime. Dodging bullets, the law, and an overbearing mother along the way, they must heal their severed family bond before they end up killing each other.",
    popularity: 807.492,
    poster_path: '/Akweo95FGyDpucYVT81h0SbX8Ky.jpg',
    release_date: '2024-10-10',
    title: 'Brothers',
    video: false,
    vote_average: 6.317,
    vote_count: 134,
  },
  {
    adult: false,
    backdrop_path: '/3rxoUVI74z7rTWYSAC2q3Uax2nC.jpg',
    genre_ids: [27, 9648],
    id: 1100782,
    original_language: 'en',
    original_title: 'Smile 2',
    overview:
      'About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.',
    popularity: 616.758,
    poster_path: '/aE85MnPIsSoSs3978Noo16BRsKN.jpg',
    release_date: '2024-10-16',
    title: 'Smile 2',
    video: false,
    vote_average: 6.9,
    vote_count: 259,
  },
  {
    adult: false,
    backdrop_path: '/m1MifWpNjOU1g8UfIyNSI2dMFZf.jpg',
    genre_ids: [16, 10751, 35, 27],
    id: 1371727,
    original_language: 'en',
    original_title: 'Sing: Thriller',
    overview:
      'Buster Moon dreams up a star-studded spectacle set to Michael Jackson\'s "Thriller" in this animated short featuring characters from the hit "Sing" films.',
    popularity: 836.816,
    poster_path: '/i77OInTKcrnRlAozFOaB6D5mk15.jpg',
    release_date: '2024-10-16',
    title: 'Sing: Thriller',
    video: false,
    vote_average: 7.32,
    vote_count: 64,
  },
];

export default nowPlayMovies;
